version: '3.8'

services:
  tietokanta-projekti:
    build: .
    depends_on:
      - mssql

  mssql:
    build:
      context: ./mssql
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Nakkikastike12"
      MSSQL_PID: "Express"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
   mssql-data: