version: '3.8'

services:
  tietokanta-projekti:
    build: .
    depends_on:
      - postgres
  
  postgres:
    build: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Nakkikastike12
      POSTGRES_DB: RecipeDB
    volumes:
      - postgres-data:/var/lib/postgresql/data
  

volumes:
  postgres-data: