version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - mssql
    command: sleep infinity

  mssql:
    build:
      context: ../mssql
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Nakkikastike12"
      MSSQL_PID: "Express"
    volumes:
      - tietokanta-projekti-mssql-data:/var/opt/mssql

volumes:
  tietokanta-projekti-mssql-data: